//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class user
    {
        public long id { get; set; }
        [DataMember(Name = "first_name")]
        public string first_name { get; set; }
        [DataMember(Name = "last_name")]
        public string last_name { get; set; }
        [DataMember(Name = "email_id")]
        public string email_id { get; set; }
        [DataMember(Name = "password",EmitDefaultValue =false)]
        public string password { get; set; }
        public bool? is_active { get; set; }
        public bool? is_locked { get; set; }
        public System.DateTime last_update { get; set; }
    }
}
